version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  bechamel-api:
    container_name: bechamel-api
    build:
      context: ./src/backend
      dockerfile: .docker/Dockerfile
    volumes:
    networks:
      - bechamel-network
    ports:
  
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  bechamel-webapp:
    container_name: bechamel-webapp
    build:
      context: ./src/frontend
      dockerfile: .docker/Dockerfile
    networks:
      - bechamel-network
    ports:
  
networks:
  bechamel-network: 
    driver: "bridge"

## docker run -d -p 45432:5432 --name team-db -e POSTGRES_PASSWORD=postgres postgres
  postgres:
    container_name: team-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=team-db
    ports:
      - 45432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/